### ISSUE TITLE
Website changes for casual visitors

### ISSUE THREAD

**Issue by KateGregory** [include-cpp/include-cpp.github.io#10]
* [x] I would like to see https://www.includecpp.org/resources/ have a table-of-contents/quicklinks down the side. 
* [x] Also, we have a section on gender neutral language (very short) then a long section on "guys" later that covers a lot of the same ground.
* [x] The CppCon CoC section is out of date.
* [x]  If someone is up for it, a general reorganization and a bunch of cheery links down the side would add value for those who aren't sure how they feel about all this yet.
* [x] add accessibility content - moved to #25

-- 

* [x] On https://www.includecpp.org/ I would like some pictures (with the consent of those pictured of course)
* [x] [decided not to do] (Maybe a separate page for the admin team, where for each of us there could be a sentence or so and assorted links as well as the current twitter links?)
* [x] I would like a big button that says Join Our Discord at the top of the main page, next to the Twitter and GitHub links. This is how we're building our community.
* [x] I think we should also list some of our channels (eg gamedev, conference-specific channels, library-specific channels, job postings, and so on.) This should emphasize mostly the "world" channels and be armwavy over any protected ones, like saying "conference-specific" instead of listing them. - moved to #26

-- 

* [x] I'd like to update What We Do because you know what? We do those things now, and more. We don't just plan to do them! Also we're fundraising to cover travel costs for under-represented attendees at conferences. And our stickers and shirts are raising awareness in workplaces all over the world.
* [x] In response to people who weren't sure they should join because they were "a straight white male" we might want to add something about when we say everyone's welcome, that's what we mean. At the table I said "if you feel the C++ community should be more welcoming and inclusive, you'll be welcomed and included." 

I would also like a "what can I do?" section that includes

 - [x] read our resources
 - [x] join our discord
 - [x] order stuff from our shop
 - [x] adopt a code of conduct at things you run
- [x] encourage things you don't run (eg conferences that want you to attend or speak) to adopt a code of conduct and enforce it
- [x] follow us on Twitter
- [x] let others know about us

--

* [x] This may result in enough sections that I want the same cheery set of side-nav links.
* [x] Down at the bottom, yes twitter, yes this form, but also mention the discord again and anyone can post in meta or DM an admin.

--

* [ ] Review and archive, if necessary, other GitHub repos - **moved to #40**
* [ ] Understand what this repo is for, and if any info should go on the website: https://github.com/include-cpp/include - **moved to #40**
* [x] Make our goals are clear in the very first paragraph of the home page. **Done as second para**
* [ ] In the accessibility links, i.e. when hitting Tab after first loading page in Chrome, "jump to content" should by-pass the side-bar menu - **moved to #39**
* [x] Move remaining actions from [the README in this repo](https://github.com/include-cpp/include-cpp.github.io) to here:

**Comment by claremacrae** [comment]
I've edited Kate's original text to convert it in to a series of check-boxes, so that we can tick stuff off as we go...
